services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  caddy:
    image: caddy:2.8.4
    environment:
        - DJANGO_ADMIN_PAGE_NAME=${DJANGO_ADMIN_PAGE_NAME}
    ports:
      - "9090:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_data:/www/static
      - media_data:/www/media
    restart: always

  backend:
    build: ./backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ADMIN_PAGE_NAME=${DJANGO_ADMIN_PAGE_NAME}
      - ALLOWED_HOST=${HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - EMAIL_PREFIX=${EMAIL_PREFIX}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - HEADLESS_URL_ROOT=https://${HOST}
      - ORCID_BASE_DOMAIN=orcid.org
      - ACCOUNT_DEFAULT_HTTP_PROTOCOL=https
      - LOG_FILE=/app/backend.log
      - DEBUG=False
    ports:
      - "8090:8080"
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    restart: always

  frontend:
    build: ./frontend
    environment:
      - ALLOWED_HOST=${HOST}
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      - ADMIN_PAGE_NAME=${ADMIN_PAGE_NAME}
      - NODE_ENV=production
      - DEBUG=False
    restart: always

  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  celery:
    build: ./backend
    command: sh -c "celery -A backend worker -l info"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  static_data:
  media_data: